- name: Add hadoop tmp directory
  ansible.builtin.file:
    path: /opt/hadoop_tmp
    owner: almalinux
    group: almalinux
    state: directory

- name: Add hdfs directory
  ansible.builtin.file:
    path: /opt/hadoop_tmp/hdfs
    owner: almalinux
    group: almalinux
    state: directory