- name: Copy pipeline scripts
  ansible.builtin.copy:
    src: /home/almalinux/edacw1/pipeline
    dest: /home/almalinux/
    owner: almalinux
    group: almalinux
    mode: "0755"
    force: yes # Overwrite existing files

- name: Zip 'utils' folder
  archive:
    path: "{{ ppl_path }}/utils"
    dest: "{{ ppl_path }}/utils.zip"
    format: zip