- name: Make DB directory
  ansible.builtin.file:
    path: "{{ db_path }}"
    state: directory
    mode: '0755'

- name: Download CATH Foldclass DB
  ansible.builtin.get_url:
    dest: "{{ db_path }}/cath_foldclassdb.tar.gz"
    url: http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz
  register: db_download_result
  until: db_download_result is succeeded
  retries: 3
  delay: 10

- name: Check if db is already extracted
  ansible.builtin.stat:
    path: "{{ cath_foldclassdb_path }}"
  register: db_check

- name: Make CATH Foldclass DB directory
  ansible.builtin.file:
    path: "{{ cath_foldclassdb_path }}"
    state: directory
    mode: '0777'
  when: not db_check.stat.exists

- name: Unpack CATH Foldclass DB archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ db_path }}/cath_foldclassdb.tar.gz"
    dest: "{{ cath_foldclassdb_path }}"
  when: not db_check.stat.exists

- name: Copy pipeline scripts
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../pipeline"
    dest: /home/almalinux/
    owner: almalinux
    group: almalinux
    mode: "0755"

- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv {{ ppl_path }}/venv
    creates: "{{ ppl_path }}/venv/bin/activate"

- name: Start virtual environment
  ansible.builtin.shell: "source {{ ppl_path }}/venv/bin/activate"

- name: Install required packages
  ansible.builtin.pip:
    requirements: "{{ ppl_path }}/requirements.txt"
    virtualenv: "{{ ppl_path }}/venv"
    virtualenv_python: python3

- name: Check if merizo repo is already copied
  ansible.builtin.stat:
    path: "{{ merizo_path }}"
  register: merizo_check

- name: Copy merizo repo
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../merizo_search"
    dest: /home/almalinux/
    owner: almalinux
    group: almalinux
    mode: "0755"
  when: not merizo_check.stat.exists

- name: Ensure Matplotlib cache directory exists
  ansible.builtin.file:
    path: /tmp/matplotlib
    state: directory
    owner: almalinux
    group: almalinux
    mode: "0777"