- name: Run Analysis Pipeline
  hosts: hostnode
  vars:
    report_bucket: "report"
    minio_access_key: "myminioadmin"
    minio_secret_key: "ajWs,GcEyoqx-u7-"
    minio_alias: "myminio"
    ppl_path: "/home/almalinux/pipeline"
    dataset: "human"
    script_args: ""
  tasks:
  - name: Ensure MinIO alias is configured
    shell: "/usr/local/bin/mc alias set {{ minio_alias }} {{ s3_url }} {{ minio_access_key }} {{ minio_secret_key }}"
  - name: Create MinIO bucket if it does not exist
    shell: "/usr/local/bin/mc mb --ignore-existing myminio/{{ report_bucket }}"
  - name: Copy pipeline scripts
    ansible.builtin.copy:
      src: /home/almalinux/edacw1/pipeline
      dest: /home/almalinux/
      owner: almalinux
      group: almalinux
      mode: "0755"
  - name: Zip 'utils' folder
    archive:
      path: "{{ ppl_path }}/utils"
      dest: "{{ ppl_path }}/utils.zip"
      format: zip
  - name: Run spark-submit
    shell: |
        spark-submit \
        --master yarn \
        --deploy-mode cluster \
        --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 \
        --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON={{ ppl_path }}/venv/bin/python \
        --conf spark.yarn.appMasterEnv.PYTHONPATH={{ ppl_path }}/venv/lib/python3.9/site-packages:$PYTHONPATH \
        --conf spark.executorEnv.MPLCONFIGDIR=/tmp/matplotlib \
        --conf spark.executorEnv.PYSPARK_PYTHON={{ ppl_path }}/venv/bin/python \
        --conf spark.executorEnv.PYTHONPATH={{ ppl_path }}/venv/lib/python3.9/site-packages:$PYTHONPATH \
        --py-files {{ ppl_path }}/utils.zip \
        --conf spark.executor.cores=4 \
        --conf spark.executor.memory=4g \
        {{ ppl_path }}/validate.py {{ dataset }} {{ script_args }} 2>&1
    register: spark_submit_output
  - name: Extract application ID
    set_fact:
      spark_application_id: "{{ spark_submit_output.stdout | regex_search('application_[0-9_]+') }}"
  - name: Print application ID
    debug:
      msg: "Spark Application ID is: {{ spark_application_id }}"