{
 "title": "Yarn cluster resource",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Merizo Search Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(merizo_search_failed[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{fstype!=\"tmpfs\", mountpoint!=\"/boot\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint!=\"/boot\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance) (   rate(node_network_receive_bytes_total[5m]) +   rate(node_network_transmit_bytes_total[5m]) )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}