- name: Set up firewall
  become: true
  become_user: root
  hosts: all
  tasks: 
  - name: Enable ufw
    ansible.builtin.shell: "echo y | ufw enable"
  - name: Allow traffic from cluster hosts
    ansible.builtin.shell: "ufw allow from {{ item }}"
    loop: "{{ query('inventory_hostnames', 'all')  }}"

# https://stackoverflow.com/questions/14582387/hadoop-datanodes-available-0-0-total-0-dead