- name: Install and configure spark
  hosts: all
  vars:
    spark_home: /home/almalinux/spark-3.5.3-bin-hadoop3-scala2.13
  tasks: 
  - name: Download spark .jar
    ansible.builtin.get_url:
      dest: /home/almalinux/spark.tgz
      url: "https://dlcdn.apache.org/spark/spark-3.5.3/spark-3.5.3-bin-hadoop3-scala2.13.tgz"
  - name: Check if Spark is already extracted
    ansible.builtin.stat:
      path: "{{ spark_home }}"
    register: spark_folder_check
  - name: Unpack tgz file
    ansible.builtin.unarchive:
      dest: /home/almalinux/
      remote_src: true
      src: /home/almalinux/spark.tgz
    when: not spark_folder_check.stat.exists
  - name: Write config file
    ansible.builtin.template:
      src: files/spark-defaults.conf.j2
      dest:  /home/almalinux/spark-3.5.3-bin-hadoop3-scala2.13/conf/spark-defaults.conf