- name: Download Human AlphaFoldDB Model Data
  hosts: hostnode
  tasks:
  - name: Make tmp directory
    ansible.builtin.file:
      path: /home/almalinux/data/tmp
      state: directory
      mode: '0755'
  - name: Download Human AlphaFoldDB models
    ansible.builtin.get_url:
      dest: /home/almalinux/data/UP000005640_9606_HUMAN_v4.tar
      tmp_dest: /home/almalinux/data/tmp
      url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar
  - name: Make Human model directory
    ansible.builtin.file:
      path: /home/almalinux/data/UP000005640_9606_HUMAN_v4
      state: directory
      mode: '0777'
  - name: Unpack Human AlphaFoldDB models archive
    ansible.builtin.unarchive:
      remote_src: true
      src: /home/almalinux/data/UP000005640_9606_HUMAN_v4.tar
      dest: /home/almalinux/data/UP000005640_9606_HUMAN_v4