- name: Download CATH Foldclass DB
  hosts: storagenode
  tasks:
  - name: Make tmp directory
    ansible.builtin.file:
      path: /home/almalinux/data/tmp
      state: directory
      mode: '0755'
  - name: Download CATH Foldclass DB
    ansible.builtin.get_url:
      dest: /home/almalinux/data/cath_foldclassdb.tar.gz
      tmp_dest: /home/almalinux/data/tmp
      url: http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz
  - name: Make CATH Foldclass DB directory
    ansible.builtin.file:
      path: /home/almalinux/data/cath_foldclassdb
      state: directory
      mode: '0777'
  - name: Unpack CATH Foldclass DB archive
    ansible.builtin.unarchive:
      remote_src: true
      src: /home/almalinux/data/cath_foldclassdb.tar.gz
      dest: /home/almalinux/data/cath_foldclassdb