- name: Reboot
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Reboot
    ansible.builtin.reboot:
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 60
      test_command: uptime