- name: Run pipeline with Ecoli dataset
  hosts: hostnode
  tasks:
  - name: Run pipeline
    include_role:
      name: pipeline
      tasks_from: run.yaml
    vars:
      dataset: ecloi
      s3url: "{{ s3_url }}"
      access_key: "{{ minio_access_key }}"
      secret_key: "{{ minio_secret_key }}"
      input_bucket: ecoli-alphafolddb
      output_bucket: ecoli-cath-parsed
      summary_bucket: cath-summary
      summary_key: ecoli-cath-parsed
      script_args: "--partitions 300"