- name: Run pipeline with Ecoli dataset
  hosts: hostnode
  tasks:
  - name: Run pipeline
    include_role:
      name: pipeline
      tasks_from: run.yaml
    vars:
      dataset: ecoli
      s3url: "{{ s3_url }}"
      access_key: "{{ minio_access_key }}"
      secret_key: "{{ minio_secret_key }}"
      input_bucket: ecoli-alphafolddb
      output_bucket: ecoli-cath-parsed
      summary_bucket: cath-summary
      summary_key: ecoli_cath_summary.csv
      mean_key: plDDT_means.csv
      script_args: "--merizo_batch_size 8 --merizo_thread_num 2 --partitions 300"