- name: Run Analysis Pipeline
  hosts: hostnode
  vars:
    ppl_path: "/home/almalinux/pipeline"
    script_args: "human"
  tasks:
  - name: Run spark-submit
    ansible.builtin.shell: |
        spark-submit \
        --master yarn \
        --deploy-mode cluster \
        --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 \
        --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON={{ ppl_path }}/venv/bin/python \
        --conf spark.yarn.appMasterEnv.PYTHONPATH={{ ppl_path }}/venv/lib/python3.9/site-packages:$PYTHONPATH \
        --conf spark.executorEnv.MPLCONFIGDIR=/tmp/matplotlib \
        --conf spark.executorEnv.PYSPARK_PYTHON={{ ppl_path }}/venv/bin/python \
        --conf spark.executorEnv.PYTHONPATH={{ ppl_path }}/venv/lib/python3.9/site-packages:$PYTHONPATH \
        --py-files {{ ppl_path }}/utils.zip \
        {{ ppl_path }}/pipeline.py {{ script_args }}
    args:
      executable: /bin/bash
    register: spark_submit_result
  - name: Show spark submit result
    ansible.builtin.debug:
      msg: "{{ spark_submit_result.stdout_lines }}"