- name: Run Analysis Pipeline
  hosts: hostnode
  vars:
    ppl_path: "/home/almalinux/pipeline"
    script_args: "UP000005640_9606_HUMAN_v4"
  tasks:
  - name: Run Spark-Submit on Master Node
    ansible.builtin.shell: |
        spark-submit \
        --master yarn \
        --deploy-mode cluster \
        --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 \
        --conf spark.executorEnv.MPLCONFIGDIR=/tmp/matplotlib \
        --conf spark.executorEnv.PYSPARK_PYTHON={{ ppl_path }}/venv/bin/python \
        --conf spark.executorEnv.PYTHONPATH={{ ppl_path }}/venv/lib/python3.9/site-packages:$PYTHONPATH \
        {{ ppl_path }}/pipeline.py {{ script_args }}
    args:
      executable: /bin/bash
    register: spark_submit_result
  - name: Show Spark Submit Result
    ansible.builtin.debug:
      msg: "{{ spark_submit_result.stdout_lines }}"