- name: Set Up Pipeline
  hosts: hostnode
  vars:
    ppl_path: "/home/almalinux/pipeline"
  tasks:
  - name: Copy pipeline scripts
    ansible.builtin.copy:
      src: /home/almalinux/edacw1/pipeline
      dest: /home/almalinux/
      owner: almalinux
      group: almalinux
      mode: "0755"
  # - name: Create Virtual Environment
  #   command: "python3 -m venv {{ ppl_path }}/spark_venv"
  #   args:
  #     creates: "{{ ppl_path }}/spark_venv"
  # - name: Install Dependencies in Virtual Environment
  #   pip:
  #     requirements: "{{ ppl_path }}/requirements.txt"
  #     virtualenv: "{{ ppl_path }}/spark_venv"
  #     virtualenv_python: python3
  # - name: Zip Virtual Environment Site-Packages
  #   command: "zip -r {{ ppl_path }}/spark_venv_dependencies.zip . -i {{ ppl_path }}/spark_venv/lib/python3*/site-packages"
  #   args:
  #     creates: "{{ ppl_path }}/spark_venv_dependencies.zip"
  # - name: start virtual environment
  #   ansible.builtin.shell: "source {{ ppl_path }}/venv/bin/activate"