- name: Prepare workers envrioment
  hosts: workers
  vars:
    db_path: "/home/almalinux/db"
    cath_foldclassdb_path: "/home/almalinux/db/cath_foldclassdb"
    ppl_path: "/home/almalinux/pipeline"
  tasks:
  - name: Make db directory
    ansible.builtin.file:
      path: "{{ db_path }}"
      state: directory
      mode: '0755'
  - name: Download CATH Foldclass DB
    ansible.builtin.get_url:
      dest: "{{ db_path }}/cath_foldclassdb.tar.gz"
      url: http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz
  - name: Check if db is already extracted
    ansible.builtin.stat:
      path: "{{ cath_foldclassdb_path }}"
    register: db_check
  - name: Make CATH Foldclass DB directory
    ansible.builtin.file:
      path: "{{ cath_foldclassdb_path }}"
      state: directory
      mode: '0777'
    when: not db_check.stat.exists
  - name: Unpack CATH Foldclass DB archive
    ansible.builtin.unarchive:
      remote_src: true
      src: "{{ db_path }}/cath_foldclassdb.tar.gz"
      dest: "{{ cath_foldclassdb_path }}"
    when: not db_check.stat.exists
  - name: Copy pipeline scripts
    ansible.builtin.copy:
      src: /home/almalinux/edacw1/pipeline
      dest: /home/almalinux/
      owner: almalinux
      group: almalinux
      mode: "0755"
  - name: Create virtual environment
    ansible.builtin.command:
      cmd: python3 -m venv {{ ppl_path }}/venv
      creates: "{{ ppl_path }}/venv/bin/activate"
  - name: Start virtual environment
    ansible.builtin.shell: "source {{ ppl_path }}/venv/bin/activate"
  - name: Install required packages
    ansible.builtin.pip:
      requirements: "{{ ppl_path }}/requirements.txt"
      virtualenv: "{{ ppl_path }}/venv"
      virtualenv_python: python3
  - name: Copy merizo repo
    ansible.builtin.copy:
      src: /home/almalinux/edacw1/merizo_search
      dest: /home/almalinux/
      owner: almalinux
      group: almalinux
      mode: "0755"
  - name: Ensure Matplotlib Cache Directory Exists
    file:
      path: /tmp/matplotlib
      state: directory
      owner: almalinux
      group: almalinux
      mode: "0777"
  # - name: add to pythonpath
  #   ansible.builtin.lineinfile:
  #     path: /home/almalinux/.bashrc
  #     insertafter: EOF
  #     line: "export PYTHONPATH=${PYTHONPATH}:/home/almalinux/merizo_search/merizo_search/programs:{{ ppl_path }}:{{ ppl_path }}/venv/lib/python3*/site-packages"
  #     state: present
  # - name: reload environment variables
  #   ansible.builtin.shell: source /home/almalinux/.bashrc