- name: Accept repo GPG key
  ansible.builtin.shell:
    cmd: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: Install node-exporter
  ansible.builtin.dnf:
    name: golang-github-prometheus-node-exporter
    state: latest

- name: Create Textfile Collector directory
  ansible.builtin.file:
    path: "{{ textfile_collector_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Update node exporter config file
  ansible.builtin.template:
    src: files/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root

- name: Start node-exporter
  ansible.builtin.service:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: true